//!! -D DEBUG
import assert;

fun sprMain
{
    if ( programArgs.size() < 2 )
        return;
    var n = programArgs(1) asInt;

    if      ( n == 1 ) test1();
    //else if ( n == 2 ) test2();
    //else if ( n == 3 ) test3();
}

fun printerTrue: Bool
{
    cout << "Inside printerTrue" << endl << flush;
    return true;
}

fun printerFalse: Bool
{
    cout << "Inside printerFalse" << endl << flush;
    return false;
}

fun test1
{
    assert(true);
    assert(false);
    assert(printerTrue());
    assert(printerTrue(), "this needs to be true");
    assert(printerFalse());
    assert(2 == 1+1);
    assert(2 != 1+1, "intentional error");
}
/*<<<All asserts are ok (1)
AssertTest.spr(30): assertion failure: check false has failed
Inside printerTrue
Inside printerTrue
Inside printerFalse
AssertTest.spr(33): assertion failure: check printerFalse() has failed
AssertTest.spr(35): assertion failure: check 2 != 1+1 has failed: intentional error
>>>*/
